import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import ReduxProvider from "@/providers/ReduxProvider";
import "./globals.css";
import Navbar from "@/components/shared/NavBar";
import Footer from "@/components/shared/Footer";
import { AuthProvider } from "@/providers/AuthProvider";
import { Toaster } from "sonner";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${roboto.variable} ${geistMono.variable} antialiased font-roboto`}>
        <ReduxProvider>
          <AuthProvider>
            {/* <Navbar /> */}
            {children}
            {/* <Footer /> */}
            <Toaster />
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
